model:
  model_id: audio_ae

  channels: 2
  latent_channels: 64
  ch_0: 256
  ch_max: 1536

  strides: [3, 5, 7, 7]

  eq: true
  checkpoint_grads: true

train:
  trainer_id: audio_rec
  data_id: s3_cod_audio
  data_kwargs:
    bucket_name: cod-yt-audio
    window_length: 88200

  target_batch_size: 32
  batch_size: 4
  epochs: 100

  opt: AdamW
  opt_kwargs:
    lr: 3.0e-5
    eps: 1.0e-15
    betas: [0.9, 0.95]
    weight_decay: 1.0e-4

  loss_weights:
    recon: 2.5
    stft: 1.5
    lr_ms_ratio: 0.5
    hubert: 0.0
    crt: 4.0
    eq: 0.25

  sample_rate: 44100
  n_fft_list: [2048, 1024, 512, 256, 128, 64, 32]

  scheduler: LinearWarmup
  scheduler_kwargs:
    warmup_steps: 1500
    min_lr: 3.0e-6

  checkpoint_dir: checkpoints/audio_ae
  resume_ckpt: null #checkpoints/audio_ae/step_70000.pt

  sample_interval: 500
  save_interval: 5000

wandb:
  name: ${env:WANDB_USER_NAME}
  project: owl_audio_vaes
  run_name: audio_ae_baseline
