model:
  channels: 64

  ####
  n_layers: 28
  n_heads: 20
  n_kv_heads: 10
  d_model: 2560
  mlp_ratio: 4

  gradient_checkpointing: false
  ####

  tokens_per_frame: 256
  height: 16
  width: 16
  patch: [1, 1]

  base_fps: 30  # FPS must be divisible by this. atomic time unit is 1/base_fps
  local_window: 8
  global_window: 32
  global_attn_period: 4

  n_frames: 1024  # num RoPE cached frames, doesn't impact model behavior

  rope_impl: ortho

  sink_attn: false
  gated_attn: true

  noise_conditioning: wan

  n_controller_inputs: 13

  cfg_prob: 0.1  # TODO: implement, currently unused


train:
  trainer_id: world

  ELBO_loss: false
  inference_matching: true
  noise_prev: 0.0089
  bidirectional_warmup: null
  noise_distribution: iid # pyoco_progressive

  total_accum_steps: 32

  data_id: multi
  data_kwargs:
    defaults:
      batch_size: 1
      seq_len: 64
      batch_columns: ["rgblatents", "fps"]
      latent_column: "rgblatents"
      sampling_periods: [1]
      legal_fps: [30]
    loaders:
      - data_id: sequence_packing
        data_kwargs:
          dataset_path: /mnt/data/waypoint_1/wm_npy/MKIF_360P/train/
          sampling_periods: [1]

  n_eval_loss_samples: 8192
  eval_data_id: multi
  eval_data_kwargs:
    defaults:
      batch_size: 1
      seq_len: 192
      batch_columns: ["rgblatents", "fps"]
      latent_column: "rgblatents"
      sampling_periods: [1]
      legal_fps: [30]
    loaders:
      - data_id: cod
        data_kwargs:
          dataset_path: /mnt/data/waypoint_1/wm_npy/MKIF_360P/eval/
          sampling_periods: [1]

  sample_data_id: multi
  sample_data_kwargs:
    defaults:
      batch_size: 1
      seq_len: 192
      batch_columns: ["rgblatents", "fps"]
      latent_column: "rgblatents"
      sampling_periods: [1]
      legal_fps: [30]
    loaders:
      - data_id: cod
        data_kwargs:
          dataset_path: /mnt/data/waypoint_1/wm_npy/MKIF_360P/eval/
          sampling_periods: [1]

  sampler_id: av_caching
  sampler_kwargs:
    n_steps: 40
    cfg_scale: 1.0
    only_return_generated: false
  sampling_batch_size: 1
  num_seed_frames: 30
  num_generated_frames: 150
  n_samples: 16  # TODO: this doesn't work, we always do 1 sample per GPU
  eval_sample_dir: null

  epochs: 10000

  opt: Muon
  opt_kwargs:
    lr: 1.0e-3
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 1.0e-4
    adamw_eps: 1.0e-6
    adamw_betas: [0.9, 0.95]
    adamw_keys: [patchify, unpatchify, _emb, cond_proj, out_norm, gate_proj]
    adamw_low_lr_keys: []
    adamw_low_lr_mul: 0.1

  scheduler: null

  checkpoint_dir: /mnt/data/waypoint_1/checkpoints/pilot_stage0
  output_path: /mnt/data/waypoint_1/models/pilot_stage0
  resume_ckpt: null

  sample_interval: 5000
  save_interval: 10000

  vae_id: null
  vae_batch_size: 4

  vae_scale: 0.73
  vae_cfg_path: /mnt/data/shahbuland/owl-vaes/configs/waypoint_1/rgb_only.yml
  vae_ckpt_path: /mnt/data/lapp0/vaes/waypoint_1_f32c64_8res_rgb_only_decoder.pt

  prompt_encoder_model_id: google/umt5-xl

  wandb_watch: false

wandb:
  name: louiscastricato  # lapp0-andrew-lapp
  project: waypoint_1  # owl
  run_name: ${oc.env:RUN_NAME}
